_wandb:
    value:
        cli_version: 0.22.3
        e:
            tnf13jm4c2ynfwa5id9vkuqoc5rlpa3t:
                args:
                    - --headless
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1021619437568"
                        used: "284756234240"
                email: xzdang13@gmail.com
                executable: /home/troja/miniconda3/envs/isaaclab/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-d59756b1-1f1b-646c-2818-22082fbcabee
                host: troja-System-Product-Name
                memory:
                    total: "134972284928"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/troja/Desktop/G1MotionTracking/train.py
                python: CPython 3.11.14
                root: /home/troja/Desktop/G1MotionTracking
                startedAt: "2026-01-05T12:36:10.072275Z"
                writerId: tnf13jm4c2ynfwa5id9vkuqoc5rlpa3t
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
            "4": 3.11.14
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
